### ISSUE TITLE
Add to OpenVSX

### ISSUE THREAD

**Issue by sbussard** [rhalaly/scope-to-this-vscode#16]
For use with code-server and other non-microsoft distributions

https://open-vsx.org/

**Comment by SamEdwardes** [comment]
I just came here to add this issue. +1!

I am happy to help if you are open to PRs. For reference, here are the instructions: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

If the author does not want to add to open-vsx, it can also be published via this repo:https://github.com/open-vsx/publish-extensions/blob/master/CONTRIBUTING.md. But this is only a backup plan; open-vsx prefers to have the authors publish directly.

**Comment by rhalaly** [comment]
@SamEdwardes any contribution will be appriciated. Feel free to open a PR

**Comment by SamEdwardes** [comment]
Hi @rhalaly, I look into the steps in more detail. They are all provided here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions, but I will summarize:

1. Create an Eclipse account
2. Log in and sign the Publisher Agreement
3. Create an access token
4. Create the namespace
5. Package and upload

I was hoping that I could help more, but unfortunately, I think these are all steps that you would have to run.

Would you be able to look into this?

If not, I can create a PR to add your package via this repo: https://github.com/open-vsx/publish-extensions/blob/master/CONTRIBUTING.md. However, the open vsx maintainers prefer to have the extension publishers publish directly.

**Comment by rhalaly** [comment]
Thanks for the guidence @SamEdwardes! After some revivals and maintanance here, I've published the extension to open-vsx: https://open-vsx.org/extension/rhalaly/scope-to-this

There is a warning that I'm not a "verified publisher". I started the process to being verified, so don't worry 😄 

Although, I haven't tested it in other distributions than VSCode itself. I hope it will work smoothly. 

I'm closing this issue for now. Please feel free to re-open it if needed. Thanks!

**Comment by SamEdwardes** [comment]
Awesome, thank you, @rhalaly. I appreciate it. If I run into any issues, I will create a new issue.
