### ISSUE TITLE
Scope to this "in new panel"

### ISSUE THREAD

**Issue by Hobart2967** [rhalaly/scope-to-this-vscode#17]
I would love to have an option to scope to a certain file tree node, but having the scoped view resulting in a separate pane.
This could be very handy for e.g. large java projects, where I scope to the tests folder, while having the file explorer being scoped to my actual implementation classes.

**Comment by rhalaly** [comment]
This is a great suggestion, and it was my initial thought when implementing this extension. Unfortunately, mimicking the file explorer view in a new panel requires implementing it from scratch, which is way beyond my capacity. 

PRs are welcome!
