### ISSUE TITLE
Context menu is attached to wrong view: "Explorer" instead of "Folders" view

### ISSUE THREAD

**Issue by mnmkay** [rhalaly/scope-to-this-vscode#18]
By default the Explorer view contains views/subviews or whatever they're called.. views like:

Folders
Open Editors,
Outline,
Timeline

Well, the Scope to This context menu opens only works in the "Folders" view of course. However, if you drag the Folders view out of the Explorer parent view, say into the secondary sidebar and/or split inside other view areas besides "Explorer", then the Scope to This menu simply no longer shows up with you right click a folder. It's missing. It only shows up if Folders is explicitly inside Explorer, though it can be placed lots of other places in the sidebar UI.

To test, try dragging Folders view outside of the Explorer container and into various different places to make sure - even in its own standalone area of the sidebar.

These two commands highlight the difference between focusing the views at issue:
Explorer: Focus on Folders View (workbench.explorer.fileView.focus)
View: Show Explorer (workbench.view.explorer)

**Comment by rhalaly** [comment]
Hi @mnmkay, I’ve attempted to reproduce the issue but was unsuccessful. The context menu remains accessible even after dragging the Folder view into a different container.

Please note that the context menu functionality is exclusive to the official Folders view in VSCode. If you’re utilizing an extension that modifies this view, the context menu may not function as expected.

**Comment by Noisysundae** [comment]
I was able to reproduce on VSCodium 1.121.03429. Changing the view condition of `scope-to-this.scope`'s when expression from `activeViewlet == 'workbench.view.explorer'` to `view == 'workbench.explorer.fileView'` (the same as that of `scope-to-this.clear`) solves the issue.
