### ISSUE TITLE
Folders with similar names greedy matched

### ISSUE THREAD

**Issue by danieliser** [rhalaly/scope-to-this-vscode#2]
Currently if you have

```
folder
folder-a
folder-b
```

and you scope `folder`, both `folder-a` and `folder-b` also appear.

Seems the folder search is using `folder*` maybe?

**Comment by rhalaly** [comment]
Hi @danieliser, it is a known issue and even appears in the README. 

VSCode doesn't support this feature natively and currently supports only glob patterns for **excluding files and folders**, with `file.exclude` in the `settings.json`. 

In this extension, I programmatically add glob patterns that **hide everything except** the folder you select. This is a tricky operation, and it has drawbacks.

There is no (or I didn't find yet😄) a glob pattern that can handle such cases under the VSCode limitation. The generated filters are in the `settings.json` under the `file.exclude` setting. If you have an idea how to exclude also `folder-a` and `folder-b` with such glob filters, please let me know 😄

**Comment by danieliser** [comment]
Wow, google's chosen solutions all look terrifying as does the current value for file.exclude haha.

That said adding an extra line after the last detecting `[a-z0-9-_]*/**` worked for me, so maybe a play off that.

`
      "folde[!r]*/**": true,
      "folder[a-z0-9-_]*/**": true
`

**Comment by rhalaly** [comment]
Your solution is good for that case, but it is not hermetic. There are more characters that this filter will not catch. Such special characters or characters from different languages such as Chines. This is exactly the issue - there is no way in VSCode to implement "all except" 😄 

And in the README I mentioned another case of a miss. If you want to scope to `folder-a` you will still see `folder` in your explorer view. This filter will not save you from that case.

I think in the meanwhile you can use for example [Explorer Exclude](https://github.com/redvanworkshop/explorer-exclude-vscode-extension) to easily, but manually, hide excess folders and files if they interrupt you.

**Comment by danieliser** [comment]
@rhalaly Appreciate the info, you can close this one as you obviously can't do much about it currenlty.

**Comment by rhalaly** [comment]
Please feel free to post new ideas if you have

**Comment by gigberg** [comment]
I have encounter with this problem today. for folder 'xxx' and folder 'xxxyyy'. There has two situation：

① **focus the short:** 
you need to focus ‘xxx‘, **and you should got the last character 'x'** of this pathname of 
file.exclude = xxx*?
which will exclude 'xxxyyy', works as espect

②**focus the long:**
you need to focus ‘xxxyyy‘, **and you should got the last character 'y'** of this pathname of 

their is no appropriate pattern, or maybe you should traverse all folder name, than find all possible ambiguous folder(with same prefix), in this example:
you should find **one ambiguous** path(in the same dir, hope this count not be to large), which is 'xxx'
then you exclude the ambiguous path use exact match: 
file.exclude = xxx/*

Another approach:
or you may just **use exact glob pattern**( xxx/*), when it comes to subfolder of the same parent (of the scoped subfolder, assume it's 'aaa/xxx'). And then use original  exclamation mark(aa[!a]*/*)

**Comment by rhalaly** [comment]
Thanks @gigberg.

This issue is known and mentioned in the [Known Issues](https://github.com/rhalaly/scope-to-this-vscode?tab=readme-ov-file#known-issues-). Unfortunately, I couldn't find a good fix under VSCode file filtering restrictions.

You are more than welcome to contribute to this extension and solve that issue, once you find a solution!
