### ISSUE TITLE
Conflict with PHP Intelliphense extension

### ISSUE THREAD

**Issue by danieliser** [rhalaly/scope-to-this-vscode#4]
Not sure if this is fixable on either end specifically, so starting here as its always easier to get a newer project to make a change than a long established one.

So it goes like this.

1. Load up project with intelliphense.
2. Scope to a child folder that includes files that call functions/classes from the global scope. ex. a WordPress plugin within the WordPress installation that calls WP core functions.
3. Reload the window (common for variety of reasons such as extension removed etc).
4. Notice that intelliphense is now not picking up any of the functions/classes outside of the scoped folder.

Reverse is simple, unscope and "reload window" again, then scope back in.

So just off the top of my head a possible simple solution might be:

1. Detect window reload, assuming you can. Move the scope to a different storage key.
2. After reload and init, move the scope settings back into place

This could be cool in general as it could be done for closing the program and opening a project etc.

**Comment by rhalaly** [comment]
I don't think it is related directly to the extension logic. This extension just changes the `file.exclude` setting so VSCode will hide the files in the explorer view. You can try to set it manually (without this extension) and test if it works.

I think it is better to report this issue to intelliphense and explain that their extension doesn't work if you set the `file.exclude` settings.

**Comment by danieliser** [comment]
@rhalaly Technically speaking their extension works fine when you set `file.exclude` but of course any files excluded don't get indexed or show up for autocomplete etc. This is not ideal as scoped view does not designate the other stuff isn't used within.

This would likely be true for any extension that ran scans on the project.

The issue is that this scope extension is manipulating that setting for a specific gain, but since other extensions also rely on it I'd think your end likely needs to figure out how to do what it does with as little side effect as possible.

**Comment by rhalaly** [comment]
>The issue is that this scope extension is manipulating that setting for a specific gain, but since other extensions also rely on it I'd think your end likely needs to figure out how to do what it does with as little side effect as possible.

There are a lot of extensions that manipulate the `file.excludes` for hiding files for the user, like the extension that I took inspiration from. And personally, I used a lot of them for scoping before I wrote this extension.
Does everyone need to change how they manipulate the `file.exclude` setting because they can conflict with `intelephense`?

It is not so rare to have a conflict between extensions. But I (and other similar extensions) can't handle all the conflicts with all other extensions.

The alternative you suggested can't work, AFAIK. The VSCode determines the extensions' initialization order (based on their priority). So, you can't rely on that their index will always run before this extension.

I think the best solution to fix this conflict is to fork this extension and manipulate it for your needs. For example, the scope feature will write to `file.exclude` as usual, but also write to ignore it in `intelephense.files.exclude`, so their index will not use it.
The forking doesn't take too much effort. You can build your private extension locally even without publish it if you don't want to.

**Comment by danieliser** [comment]
@rhalaly - I use that exclusion list regularly too, but for its mainly intended purpose of excluding files to lower memory consumption and improve performance, such as node_modules & vendors folders etc.

I understand that is likely the only feasible way you can accomplish this given the limitations of VS Code cores exposed APIs.

---

The solution you proposed won't do what I'm after, at least not as proposed, I'm looking for intelliphense to index those files, thus they should not be excluded when that happens.

It does appear that the indexer middleware kicks off pretty much immediately so load order is as you pointed out an issue here.

That said I did dig into their code and found that they register a command to force reindexing.

I'm wondering if a possible solution might be to add an option for this extension that if set runs a small loop that could be used to counter this on a per user basis, without complexities of making it work with each of them yourself.

Trust me I understand the balance of interacting inside a huge open source plugin/extension based ecosystem. I created and run a top 100 WordPress plugin with over 600k users that integrates very tightly with dozens of other 3rd party WP plugins. ([Popup Maker](https://wordpress.org/plugins/popup-maker) for reference).

What I'm wondering if you'd consider might look like this (pseudo code) during your activation process, and may need some tweaking obviously to get just right, but I haven't studied your plugin's code directly just yet.

    if ( preActivation.length ) {
        // 1. Disable current scope and set it into a variable.
        // 2. For each preActivation VSC Command or function, check if it exists and call it.
        // 3. Reactivate current scope from earlier.
    }

In this way we could register a custom setting as an array of [CMD]. Not sure functions are feasible as I haven't really studied how much interaction is possible between extensions without a fully exposed CMD, so it may just be CMDs.

But in this way at least there is feasibly a way to get around it when it is an issue.

Just to be clear, I see this issue several times a day, just one of those annoying things I'm trying to live with until a solution is worked out.

Ideally there would be another way for you to manage the scope rather than file.exclude but it is what it is for now until VSC core changes I imagine.

**Comment by rhalaly** [comment]
I'm closing this issue as I don't have any alternative for implementing this logic. PR are welcom to assist with this issue
